export default {
    omitProperties: {
        ACCESS_REQUEST_CONFIG: [
            "$.approvalReminderAndEscalationConfig.fallbackApproverRef.id",
        ],
        ATTR_SYNC_SOURCE_CONFIG: ["$.source.id"],
        BRANDING_CONFIG: ["$.[*].standardLogoURL"],
        CONNECTOR_SCHEMA: ["$.attributes[*].schema.id"],
        FORM_DEFINITION: [
            "$.id",
            "$.created",
            "$.modified",
            "$.owner.id",
            "$.usedBy"
        ],
        GLOBAL: ["$.id", "$.created", "$.modified"],
        GOVERNANCE_GROUP: ["$.owner.id"],
        IDENTITY_OBJECT_CONFIG: [
            "$[?(@.name == 'manager' || @.name == 'uid')]",
        ],
        IDENTITY_PROFILE: [
            "$.self.id",
            "$.object.id",
            "$.object.created",
            "$.object.modified",
            "$.object.owner.id",
            "$.object.authoritativeSource.id",
            "$.object.identityAttributeConfig.attributeTransforms[?(@.transformDefinition.type == 'rule')].transformDefinition.attributes.id",
            "$.object.identityAttributeConfig.attributeTransforms[?(@.transformDefinition.type == 'reference')].transformDefinition.attributes.input.attributes.sourceId",
            "$.object.identityAttributeConfig.attributeTransforms[?(@.transformDefinition.type == 'accountAttribute')].transformDefinition.attributes.sourceId",
            "$.object.identityCount",
        ],
        LIFECYCLE_STATE: ["identityCount"],
        ORG_CONFIG: ["$.modifiedBy"],
        PASSWORD_POLICY: ["$.dateCreated", "$.lastUpdated"],
        SERVICE_DESK_INTEGRATION: [
            "$.ownerRef.id",
            "$.clusterRef.id",
            "$.provisioningConfig.managedResourceRefs[*].id",
            "$.beforeProvisioningRule.id",
        ],
        SOURCE: [
            "$.owner.id",
            "$.cluster.id",
            "$.accountCorrelationConfig.id",
            "$.accountCorrelationRule.id",
            "$.managerCorrelationRule.id",
            "$.beforeProvisioningRule.id",
            "$.schemas[*].id",
            "$.passwordPolicies[*].id",
            "$.connectorAttributes.cloudExternalId",
            "$.connectorAttributes.slpt-source-diagnostics",
            "$.connectorAttributes.cloudCacheUpdate",
            "$.connectorAttributes.deltaAggregation",
            "$.connectorAttributes.healthy",
            "$.connectorAttributes.since",
            "$.connectorAttributes.status",
            "$.connectorAttributes.accountDeltaToken",
            "$.connectorAttributes.groupMembershipDeltaToken",
            "$.connectorAttributes.subscribedSkus",
            "$.status",
            "$.since",
            "$.healthy",
            "$.accountsFile",
        ],
        WORKFLOW: ["$.modifiedBy", "$.creator", "$.owner.id"],
    },
};
